name: CI

on: [pull_request]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run CI
        run: bash ./scripts/run_ci_tasks.sh -a
  ios:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: Run CI
        run: bash ./scripts/run_ci_tasks.sh -i
