name: Release

on:
  push:
    #tags:
      #- "[0-9]+.[0-9]+.[0-9]+*"
    branches:
       - MOBILE-1287

jobs:   
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Set up Node.js
        uses: actions/setup-node@master
      - name: Run Android CI
        run: bash ./scripts/run_ci_tasks.sh -a
        
  ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run iOS CI
        run: bash ./scripts/run_ci_tasks.sh -i
        
  publish_docs:
    runs-on: ubuntu-latest
    #needs: [android, ios]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Generate docs
        run: |
          npm install .
          npm run-script generate-docs
      - name: Generate library version
        id: lib_version
        run: |
         LIB_VERSION=$(cat package.json \
         | grep version \
         | head -1 \
         | awk -F: '{ print $2 }' \
         | sed 's/[",]//g' \
         | tr -d '[[:space:]]')
         echo ::set-output name=lib_version::${LIB_VERSION}
      - name: Clone mobile doc repo
        uses: actions/checkout@v2
        with:
          repository: urbanairship/mobile-docs
          token: ${{ secrets.GitHub_PAT }}
      - name: Add documentation and commit
        run: |
         ls -a
         cd mobile-docs
         bash add.sh react-native ../out $LIB_VERSION
        #git add .
        #git commit -a -m "Added docs for react-native v${LIB_VERSION}"
        #git push origin master
        
  publish:
    runs-on: ubuntu-latest
    needs: [android, ios, publish_docs]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Publish library
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        
  finished:
    runs-on: ubuntu-latest
    needs: [android, ios, publish_docs, publish]
    steps:
      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ":raised_hands: Airship React native Plugin Released! :raised_hands:"
          url: ${{ secrets.MOBILE_SLACK_WEBHOOK }}
