name: Release

on:
  push:
    #tags:
      #- "[0-9]+.[0-9]+.[0-9]+*"
    branches:
       - MOBILE-1287

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
  android:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@master
      - name: Run Android CI
        run: bash ./scripts/run_ci_tasks.sh -a
        
  ios:
    runs-on: macos-latest
    needs: checkout
    steps:
      - name: Run iOS CI
        run: bash ./scripts/run_ci_tasks.sh -i
        
  publish_docs:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Generate docs
        run: |
          npm install .
          npm run-script generate-docs
      - name: Generate library version
        id: build_name
        run: |
         LIB_VERSION=$(cat package.json \
         | grep version \
         | head -1 \
         | awk -F: '{ print $2 }' \
         | sed 's/[",]//g' \
         | tr -d '[[:space:]]')
         echo ::set-output name=build_name::${BUILD_NAME}
      - name: Clone mobile doc repo and add doc
        run: |
         git clone git@github.com:urbanairship/mobile-docs.git
         cd mobile-docs
         bash add.sh react-native ../out $LIB_VERSION
      - name: Commit the doc
        run: |
        #git add .
        #git commit -a -m "Added docs for react-native v${LIB_VERSION}"
        #git push origin master
         
  publish:
    runs-on: ubuntu-latest
    needs: [android, ios]
    steps:
      #- run: npm publish --access public
      - uses: codfish/semantic-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        
  finished:
    runs-on: ubuntu-latest
    needs: [android, ios, publish_docs, publish]
    steps:
      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ":raised_hands: Airship React native Plugin Released! :raised_hands:"
          url: ${{ secrets.MOBILE_SLACK_WEBHOOK }}
